version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CUSTOMER_BILLING_PORTAL
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - '8081:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3337:3336'
    environment:
      NODE_ENV: development
      JWT_SECRET: your-secret-key
      JWT_EXPIRATION_TIME: 30d
      ADMIN_EMAIL: your-email@gmail.com # change this for ur google email, for role admin purpose
      PROJECT_DB_HOST: postgres
      PROJECT_DB_PORT: 5432
      PROJECT_DB_USERNAME: postgres
      PROJECT_DB_PASSWORD: postgres
      PROJECT_DB_DATABASE: CUSTOMER_BILLING_PORTAL
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
